Added new entities.
RnkkTraining/Oleh-Petrenko-1 pull request #12
Opened 2016-09-16 13:23 UTC by OlehPetrenko

2016-09-17 06:50 UTC, RnkkTraining requested changes
Please, remove dependencies from unit tests.

2016-09-17 06:50 UTC, RnkkTraining commented on SortApp/SortApp.ViewModel/MainWindowViewModel.cs
> +			this.SortingAlgorithmSelection = new Dictionary<string, SortingAlgorithmKind>
I think that initializing of this dictionary should be moved to separate class. Filling of this selection should not be responsibility of this view model.

2016-09-17 06:50 UTC, RnkkTraining commented on SortApp/SortApp.ViewModel/MainWindowViewModel.cs
> +			set;
I don't think that it should be possible to set this property from outside. Consider making setter private.

2016-09-17 06:50 UTC, RnkkTraining commented on SortApp/SortApp.BL/SortingAlgorithmKindEnum.cs
> +		Bubble,
Please, specify values for enum members.
Bubble = 0,
Insertin = 1 etc.
It's also internal guideline

2016-09-17 06:50 UTC, RnkkTraining commented on SortApp/SortApp.BL/SortEngine.cs
> +		public string Sort<T>(string incomingArr, Sorter<T> sorter, IArrayGenerator<T> arrayGenerator,
I think arrayGenerator and itemConverter should be injected through constructor, not through method.
The reason for this is that this two classes do not depend from user input.
Regarding sorter - it's good that it's injected through method as in this way we could use the same engine instance even when user selects different algorithm (different sorter will be injected).

2016-09-17 06:50 UTC, RnkkTraining commented on SortApp/SortApp.BL/ItemsConvertors/ConverterStringToInt.cs
> +	public sealed class ConverterStringToInt<T> : ISortItemsCoverter<int>
This class shouldn't be generic as we know that it's related to int.

2016-09-17 06:50 UTC, RnkkTraining commented on SortApp/SortApp.BL/ArrayGenerators/ArrayGenerator.cs
> +		public T[] GenerateFromString(string arr, ISortItemsCoverter<T> itemConverter)
i think that itemConverter should be injected through constructor as it do not change during application work process.

2016-09-19 11:00 UTC, RnkkTraining commented on SortApp/SortApp.BL/ItemsConvertors/ConverterStringToInt.cs
> +			return value == string.Empty ? 0 : System.Convert.ToInt32(value);
This check is redundant as same check is already done above.

2016-09-19 11:01 UTC, RnkkTraining commented on SortApp/SortApp.BL/Data.cs
> +        /// <summary>
Please, check if alignment is OK is Visual Studio.

2016-09-19 11:01 UTC, RnkkTraining commented on SortApp/SortApp.BL/ArrayGenerators/ArrayGenerator.cs
> +		private ISortItemsCoverter<T> itemsConverter;
Fields should be placed before all other members of type.

2016-09-19 11:03 UTC, RnkkTraining commented on SortApp/SortApp.BL.Test/ConverterStringToIntTests.cs
> +			int expected = 0;
This part is redundant as we expect exception

2016-09-19 11:03 UTC, RnkkTraining commented on SortApp/SortApp.BL.Test/ConverterStringToIntTests.cs
> +			Assert.AreEqual(expected, result);
This part is redundant as we expect exception

2016-09-19 11:06 UTC, RnkkTraining commented on SortApp/SortApp.BL.Test/ArrayGeneratorTests.cs
> +			CollectionAssert.AreEqual(expected, result);
This part is redundant as we expecting exception.

2016-09-19 11:06 UTC, RnkkTraining commented on SortApp/SortApp.BL.Test/ArrayGeneratorTests.cs
> +			int[] expected = { };
This line is redundant as we expecting exception.

2016-09-19 11:07 UTC, RnkkTraining commented on SortApp/SortApp.ViewModel/MainWindowViewModel.cs
> +			this.ClickCommandSort = new Command(arg => ClickMethodSort());
Consider using short delegate form (just pass the method name):
new Command(this.ClockMethodSort);

2016-09-19 11:07 UTC, RnkkTraining commented on SortApp/SortApp.ViewModel/MainWindowViewModel.cs
> +			set
Setter could be made private as it should only be possible to set results from inside of this view model.

2016-09-19 11:07 UTC, RnkkTraining commented on SortApp/SortApp.Presentation/MainWindow.xaml
>              <RowDefinition Height="*"></RowDefinition>
Tag could be closed in opening tag (as in tag above)

2016-09-19 11:07 UTC, RnkkTraining commented on SortApp/SortApp.BL/SorterFactory.cs
> +			if (algorithmKind == SortingAlgorithmKind.Bubble)
I suggest to change numerous if statements to switch/case.

2016-09-19 11:07 UTC, RnkkTraining commented on SortApp/SortApp.BL/SorterFactory.cs
> +			return new InsertionSort<T>();
InsertionSort should only be returned when SortingAlgorithmKind.Insertion comes to method.
In case none of conditions about are passed - i suggest to throw NotSupportedException.

2016-09-19 11:07 UTC, RnkkTraining commented on SortApp/SortApp.BL/SortEngine.cs
> +			foreach (var item in array)
Please, specify type expicitly (instead of using var).

2016-09-19 11:07 UTC, RnkkTraining commented on SortApp/SortApp.BL/ItemsConvertors/ConverterStringToInt.cs
> +				throw new NullReferenceException();
ArgumentNullException is more suitable here in my opinion.
Reason - NullReference mostly mean that called method has some bug.
ArgumentNullException means that parameter passed to method is null (which is not expected). In this way it's clear that it's caller who has bug.

2016-09-19 11:24 UTC, OlehPetrenko commented on SortApp/SortApp.BL.Test/ArrayGeneratorTests.cs
> +			CollectionAssert.AreEqual(expected, result);
@RnkkTraining Why we expecting excepting? In this test we expecting empty array.

2016-09-19 12:45 UTC, RnkkTraining approved these changes

2016-09-19 12:45 UTC, merged